version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 6666:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  php-fpm:
    image: bitnami/php-fpm
    # build:
    #   context: .
    #   dockerfile: Dockerfile-php
    environment:
      DB_NAME: university
      DB_USER: test
      DB_PASSWORD: test
      DB_PORT: 3306
      DB_HOST: mysql
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: university
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 6001:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend
networks:
    frontend:
    backend: