version: "3.19"
services:
  nginx:
    build:
      context: ./nginx
      args:
        - PORT=${NGINX_PORT}
    restart: always
    ports:
      - 6666:${NGINX_PORT}
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NGINX_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  php-fpm:
    image: clearlinux/php-fpm:8.2.6
    restart: always
    environment:
      DB_NAME: university
      DB_USER: db_user
      DB_PASSWORD: /run/secrets/mysql_password
      DB_PORT: 3306
      DB_HOST: mysql
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend
    secrets:
      - mysql_password
      - mysql_root_password

  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: university
      MYSQL_USER: db_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
    secrets:
      - mysql_password
      - mysql_root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 6001:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend

networks:
  frontend:
  backend:

secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
